### ISSUE TITLE
Key space names are handled incorrectly when the new name includes the old one

### ISSUE THREAD

**Issue by bitcalc** [AppliedInfrastructure/cassandra-snapshot-tools#13]
Do you have the plan to support the new version of Cassandra? When I run it on Cassandra 3.11.2, putSnapshot gives lots of errors.

**Comment by bitcalc** [comment]
It turns out to be a bug in the putSnapshot program. My old keyspace is 'emailks' and I use a new name which is an extension of the old keyspace name 'emailks_dev'. The program generates names like 'emailks_dev_dev' with bash string replacement. The schema file has invalid CQL statement:
`CREATE KEYSPACE sgemail_dev.dev WITH replication...`

**Comment by mikelaws** [comment]
I think we can call this one done for now - if any issues creep up, please re-open.  Thanks for the merge request!
