### ISSUE TITLE
Error finding required executables: cqlsh

### ISSUE THREAD

**Issue by ksachdeva11** [AppliedInfrastructure/cassandra-snapshot-tools#6]
When I run the script Im seeing the following error. I have placed the script in `/Users/ksachdeva/dse/bin` directory. Any idea ?

```
Kunals-Mac:bin ksachdeva$ ./getSnapshot -k admin -s admin.backup -y ../resources/cassandra/conf/cassandra.yaml
Error finding required executables: cqlsh
```

**Comment by mikelaws** [comment]
Hi @ksachdeva11 - It looks like getSnapshot is unable to find the cqlsh executable by searching in your users' PATH.  GetSnapshot assumes you're running on a host that has Cassandra, cqlsh, and several other dependencies installed.  You may need to add `/Users/ksachdeva/dse/bin` to your PATH (by editing `~/.bash_profile` or similar).

**Comment by mikelaws** [comment]
Hi @ksachdeva11 - I'm going to go ahead and close this issue.  Please re-open if you still have dependency issues with getSnapshot.
